package Functionality;

import DatabaseIntergration.DatabaseMethods;
import impl.Answers;
import impl.ExamStudent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;

public class AnswersManager {

    private final DatabaseMethods dbmethods;
    int id;
    String name;
    String quest1;
    String quest2;
    String quest3;

    public AnswersManager() {
        this.dbmethods = new DatabaseMethods();
    }

    public int saveAnswers(String quest1, String quest2, String quest3, int exam_id) throws SQLException {
// get autogenerated ids from save exam method
        ResultSet rs = dbmethods.saveExam(quest1, quest2, quest3);
        int answer_id;
        int inserted_rows = 0;
        while (rs.next()) {
            answer_id = rs.getInt(1);
            inserted_rows = dbmethods.updateExamStudAnswer(exam_id, answer_id);
        }
        return inserted_rows;
    }

    public ObservableList getAnswersForExamForStudent(int student_exam_id) throws SQLException {
        ObservableList<Answers> answers = FXCollections.observableArrayList();
        ResultSet rs = dbmethods.answersForExamForStudent(student_exam_id);
        while (rs.next()) {
            id = rs.getInt("id");            
            String quest1 = rs.getString("quest1");
            String quest2 = rs.getString("quest2");
            String quest3 = rs.getString("quest3");                        
            answers.add(new Answers(id, quest1, quest2, quest3));
//  New object of type Student            
        }
        return answers;
    }

}
